version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    networks:
      rede_wan:
        ipv4_address: 192.168.47.20
        aliases:
          - omeusitio.lan
      my_network:
        ipv4_address: 192.168.46.40       
    volumes:
      - ./nginx/vhost.conf:/etc/nginx/conf.d/vhost.conf
      - ./ssl:/etc/ssl
  apache1:
    hostname: apache
    build: apache
    networks:
      my_network:
        ipv4_address: 192.168.46.50

    volumes:
      - ./apache/balanceador.conf:/etc/apache2/sites-enabled/balanceador.conf
      - ./omeusitio.lan:/var/www/omeusitio.lan

  apache2:
    hostname: apache2
    build: apache
    networks:
      my_network:
        ipv4_address: 192.168.46.51

    volumes:
      - ./apache/balanceador.conf:/etc/apache2/sites-enabled/balanceador.conf
      - ./omeusitio.lan:/var/www/omeusitio.lan

  apache3:
    hostname: apache3
    build: apache
    networks:
      my_network:
        ipv4_address: 192.168.46.52

    volumes:
      - ./apache/balanceador.conf:/etc/apache2/sites-enabled/balanceador.conf
      - ./omeusitio.lan:/var/www/omeusitio.lan

  cliente:
    hostname: cliente
    build: cliente
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    networks:
      rede_wan:
        ipv4_address: 192.168.47.150
      



networks:
  my_network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.46.0/24
  rede_wan:
    ipam:
      driver: default
      config:
        - subnet: 192.168.47.0/24  